### ISSUE TITLE
2.4-2.5: Update dependencies when using spring-boot-starter-parent

### ISSUE THREAD

**Issue by fabapp2** [openrewrite/rewrite-spring#126]
**Condition**
- `pom.xml` has `spring-boot-starter` defined as parent
-  version is 2.4.x

**Recipe**
- Change version of parent to 2.5.6

**Report**
The Spring Boot version must be updated to 2.5.6.

Relevance
The scan found a dependency to Spring Boot 2.4.12 as parent to the Maven build file pom.xml.

Todo
❏ Change the version of the referenced spring-boot-starter-parent in pom.xml from <version> to 2.5.6.

**Comment by fabapp2** [comment]
Implemented in `spring-boot2-upgrade-version.yml`

```
  - org.openrewrite.maven.UpgradeParentVersion:
      groupId: org.springframework.boot
      artifactId: spring-boot-starter-parent
      newVersion: 2.5.x
```
