### ISSUE TITLE
Problems when executing the recipe SpringBootPropertiesManual_2_5

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite-spring#133]
Good afternoon,

In the recipe org.openrewrite.java.spring.boot2.SpringBootPropertiesManual_2_5 the following property changes are defined:

https://github.com/openrewrite/rewrite-spring/blob/1121fe5b9bf069553c51e6c35a8400a4d69c74d4/src/main/resources/META-INF/rewrite/spring-boot-configuration-migration-manual.yml#L62-L73

and I have defined in my application.yml

```
spring:
   datasource:
       initialization-mode: always
       platform: h2
       url: jdbc:h2:mem:testdb;MODE=Oracle;
       driver-class-name: org.h2.Driver
```
I expect something like

```
spring:
   datasource:
       url: jdbc:h2:mem:testdb;MODE=Oracle;
       driver-class-name: org.h2.Driver
   sql:
      init:
         enabled: always
         platform: h2
```
when applying mvn rewrite:run it is observed that the resulting application.yml file is not correct

```
spring:
   datasource:
       url: jdbc:h2:mem:testdb;MODE=Oracle;
       driver-class-name: org.h2.Driver

   sql:
      init:
         enabled: always

   sql:
      init:
         platform: h2
```
