### ISSUE TITLE
ExpandProperties recipe: Map type properties are not nested correctly when updated.

### ISSUE THREAD

**Issue by josemariavillar** [openrewrite/rewrite-spring#135]
Good afternoon, 

I am having problems running the ExpandProperties recipe, I can't get it to work correctly.

When running the ExpandProperties recipe in the following application.yml:

```
management: test
spring:
   mail:
     protocol: smtp
     properties.mail.smtp.connectiontimeout: 5000
     properties.mail.smtp.timeout: 5000
     properties.mail.smtp.writetimeout: 5000
```

By logic, we would expect something like:

```
management: test
spring:
   mail:
     protocol: smtp
     properties:
       mail:
         smtp:
           connectiontimeout: 5000
           timeout: 5000
           writetimeout: 5000
```

But when we run this recipe the result obtained is:

```
management: test
spring:
   mail:
     protocol: smtp
     properties:
       mail:
         smtp:
           connectiontimeout: 5000
     properties:
       mail:
         smtp:
           timeout: 5000
     properties:
       mail:
         smtp:
           writetimeout: 5000
```
