### ISSUE TITLE
ExpandProperties recipe: Map type properties are not nested correctly when updated. Part II

### ISSUE THREAD

**Issue by ruben-garciapariente** [openrewrite/rewrite-spring#161]
Hello,

[This is problaby related to https://github.com/openrewrite/rewrite-spring/issues/135](https://github.com/openrewrite/rewrite-spring/issues/135)

Using the snapshot version 4.15 I added to ExpandPropertiesTest 
```kotlin
    @Test
    fun mapTypePropertiesNotNestedCorrectly2(@TempDir tempDir: Path) = assertChanged(
            before = tempDir.resolve("application.yml").toFile().apply {
                writeText("""
server.context-path: /context
server:
  port: 8888
customize:
  group1:
    key1: value1
  group2:
    key2: value2        
            """.trimIndent())},
            after = """
server:
  context-path: /context
  port: 8888
customize:
  group1:
    key1: value1
  group2:
    key2: value2        
        """
    )
```

And the result was
```
org.opentest4j.AssertionFailedError: 
expected: "server:
  context-path: /context
  port: 8888
customize:
  group1:
    key1: value1
  group2:
    key2: value2        "
 but was: "
  server:
    context-path: /context
  server:
    port: 8888
  customize:
    group1:
      key1: value1
    group2:
      key2: value2        "
<Click to see difference>
```

As you can see there two "server:" roots

Many thanks & regards
