### ISSUE TITLE
Remove duplicate keys in yaml

### ISSUE THREAD

**Issue by traceyyoshima** [openrewrite/rewrite-spring#210]
In Yaml, a key may contain `.` like `a.b.c:true`.
In Spring, the values are resolved like properties so multiple values may be mapped to a single configuration property.

```yaml
--- 
a: 
  b: 
    c: true
  b.c: ~
a.b: 
  c: false

```

@sanagaraj-pivotal requested a recipe to remove the duplicate keys.
This issue is to discover the requirements and add the new recipe.

Questions:
- Which value does Spring use in the case of conflicts?
