### ISSUE TITLE
Replace String literals with constants for HttpHeaders and MediaTypes

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-spring#325]
Spring defines various [constants for HttpHeaders](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpHeaders.html) and [MediaTypes](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/MediaType.html).
These `_VALUE`  suffixed [constants can replace String literals](https://github.com/openrewrite/rewrite/blob/main/rewrite-java/src/main/java/org/openrewrite/java/ReplaceStringLiteralWithConstant.java#L40).

This recipe would likely consist of an extended version of this first start:
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: ReplaceStringLiteralsWithMediaTypeConstants
displayName: Replace String literals with MediaType constants
description: Replace String literals anywhere in the code with fully qualified MediaType constants.
recipeList:
  - org.openrewrite.java.ReplaceStringLiteralWithConstant:
      fullyQualifiedConstantName: org.springframework.http.MediaType.APPLICATION_JSON_VALUE
  - org.openrewrite.java.ReplaceStringLiteralWithConstant:
      fullyQualifiedConstantName: org.springframework.http.MediaType.TEXT_PLAIN_VALUE
```

Optional to tag onto this recipe another recipe that [converts the FQN to static imports](https://docs.openrewrite.org/reference/recipes/java/usestaticimport) where possible, for more readable code.

As the [Spring RequestMapping annotations](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestMapping.html) take String literals as arguments, these recipes could be a nice way to potentially clean that up a bit to use framework provided constants.
