### ISSUE TITLE
ChangeSpringPropertyKey incorrectly copies top level comments and does not preserve initial format for yml property files

### ISSUE THREAD

**Issue by iparadiso** [openrewrite/rewrite-spring#353]
We noticed a few issues with `org.openrewrite.java.spring.ChangeSpringPropertyKey` recipe pertaining to YAML config files. 

* YAML structure is not preserved and rewritten properties are added as single line format.
* Comments are incorrectly copied for multi-document yaml files.  See example below

I tested using the following recipes to rewrite 2 properties.
```
- org.openrewrite.java.spring.ChangeSpringPropertyKey:
      oldPropertyKey: spring.sleuth.enabled
      newPropertyKey: management.tracing.enabled
 - org.openrewrite.java.spring.ChangeSpringPropertyKey:
      oldPropertyKey: spring.sleuth.sampler.probability
      newPropertyKey: management.tracing.sampling.probability
```

Application config before apply ChangeSpringPropertyKey recipe
```
# comment 1
spring:
  application:
    name: testapp
  sleuth:
    sampler:
      probability: 0.1
    enabled: true

---
# overrides for staging
spring:
  config:
    activate:
      on-profile: staging
  sleuth:
    sampler:
      probability: 1.0
```
Application config after applying ChangeSpringPropertyKey recipe.  As we can see the original format is not preserved causing the order of the properties to be appended to the end of the document.  Also for multi-document sections, it incorrectly copies top level comments to the rewritten property.  

```
# comment 1

spring:
  application:
    name: testapp
management.tracing.enabled: true
management.tracing.sampling.probability: 0.1

---
# overrides for staging
spring:
  config:
    activate:
      on-profile: staging
# overrides for staging
management.tracing.sampling.probability: 1.0
```
--------- Expected Behavior ------------------

* original YAML format is preserved
* Multi-document sections have consistent property copying logic
