### ISSUE TITLE
spring-boot-22 Recipe messes up logging.file.* in application.yaml

### ISSUE THREAD

**Issue by Philzen** [openrewrite/rewrite-spring#436]
I am using the shell command from https://docs.openrewrite.org/recipes/java/spring/boot2/upgradespringboot_2_2#usage

```
mvn -U org.openrewrite.maven:rewrite-maven-plugin:run \
  -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:RELEASE \
  -Drewrite.activeRecipes=org.openrewrite.java.spring.boot2.UpgradeSpringBoot_2_2
```
to migrate a project from 2.1.18.RELEASE to latest 2.2.

Using maven 3.9.4 and java 11.0.20.1-tem

The `application.yaml` file looks like this before:

```yaml
logging:
  file:
    max-size: 10MB
    max-history: 10
    path: ${user.home}/some-folder
```

but after running above OpenRewrite recipe it looks like this:

```yaml
logging:
  file.name:
    max-size: 10MB
    max-history: 10
    path: ${user.home}/some-folder
```

this seems to be closely connected to #432 – very similar problem, but this time with a yaml style configuration file.
