### ISSUE TITLE
Recipe for migration properties configuration to yaml configuration (and vice versa)

### ISSUE THREAD

**Issue by murdos** [openrewrite/rewrite-spring#509]
## What problem are you trying to solve?
Migration of an existing application that uses properties for Spring configuration to use of YAML for Spring configuration.

## What precondition(s) should be checked before applying this recipe?
Existence of `application*.properties` files.

## Describe the situation before applying the recipe
`src/main/resources/config/application.properties`
```properties
server.port=${PORT:8080}
logging.level.org.atmosphere = warn
spring.mustache.check-template-location = false
```

## Describe the situation after applying the recipe
`src/main/resources/config/application.yml`
```yaml
server:
  port: ${PORT:8080}
logging:
  level:
    org.atmosphere: warn
spring:
  mustache:
    check-template-location: false
```
