### ISSUE TITLE
Spring 2.7: Recipe to replace getById with getReferenceById

### ISSUE THREAD

**Issue by lucashan** [openrewrite/rewrite-spring#515]
## What problem are you trying to solve?

As of Springboot v2.7, both `getOne()` and `getById()` methods have been deprecated for `JpaRepository`. The [documentation](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html) states that these deprecated methods should be replaced with `getReferenceById(ID)`.

We should include this recipe for Spring 2.7, for example:
```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.data.UseJpaRepositoryGetReferenceById
displayName: Use `JpaRepository#getReferenceById(ID id)`
description: '`JpaRepository#getById(ID)` was deprecated in 2.7.'
recipeList:
  - org.openrewrite.java.ChangeMethodName:
      methodPattern: org.springframework.data.jpa.repository.JpaRepository getById(..)
      newMethodName: getReferenceById
```

## Describe the situation before applying the recipe

```java
import org.springframework.data.jpa.repository.JpaRepository;

public interface TestRepository extends JpaRepository<Test, Long> {
}
```

```java
    public Test getTestById(final long id) {
        return testRepository.getOne(id);
    }
```

## Describe the situation after applying the recipe

```java
import org.springframework.data.jpa.repository.JpaRepository;

public interface TestRepository extends JpaRepository<Test, Long> {
}
```

```java
    public Test getTestById(final long id) {
        return testRepository.getReferenceById(id);
    }
```

## Have you considered any alternatives or workarounds?

N/A
