### ISSUE TITLE
Removing an annotation from a class may result in an extra empty line

### ISSUE THREAD

**Issue by wapkch** [openrewrite/rewrite-spring#659]
## What version of OpenRewrite are you using?

I am using

- rewrite-spring 5.25.0

## How are you running OpenRewrite?
Unit Tests.

## What is the smallest, simplest way to reproduce the problem?

The issue can be reproduced with the following code snippet:
```java
class RemoveEnableBatchProcessingTest implements RewriteTest {

    @Override
    public void defaults(RecipeSpec spec) {
        spec.recipe(new RemoveEnableBatchProcessing())
          .parser(JavaParser.fromJavaVersion().classpath("spring-batch-core", "spring-boot"));
    }

    @Test
    void removeSpringBatchAnnotation() {
        rewriteRun(
          //language=java
          java(
            """
              import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
              import org.springframework.boot.autoconfigure.SpringBootApplication;
                            
              @EnableBatchProcessing
              @SpringBootApplication
              public class Application {
              }
              """,
            """
              import org.springframework.boot.autoconfigure.SpringBootApplication;
                            
              @SpringBootApplication
              public class Application {
              }
              """
          )
        );
    }

    @Test
    void removeSpringBatchAnnotation2() {
        rewriteRun(
          //language=java
          java(
            """
              import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
              import org.springframework.boot.autoconfigure.SpringBootApplication;
                            
              @SpringBootApplication
              @EnableBatchProcessing
              public class Application {
              }
              """,
            """
              import org.springframework.boot.autoconfigure.SpringBootApplication;
                            
              @SpringBootApplication
              public class Application {
              }
              """
          )
        );
    }
}
```

## What did you expect to see?

I expected both test methods (removeSpringBatchAnnotation and removeSpringBatchAnnotation2) to run successfully.

## What did you see instead?

The removeSpringBatchAnnotation test method passed successfully, but the removeSpringBatchAnnotation2 method failed with following error:

```css
org.opentest4j.AssertionFailedError: [Unexpected result in "Application.java":
diff --git a/Application.java b/Application.java
index 0eaa8a0..7bbfe15 100644
--- a/Application.java
+++ b/Application.java
@@ -1,5 +1,6 @@ 
 import org.springframework.boot.autoconfigure.SpringBootApplication;
 
+
 @SpringBootApplication
 public class Application {
 }
\ No newline at end of file
] 
expected: 
  "import org.springframework.boot.autoconfigure.SpringBootApplication;
  
  @SpringBootApplication
  public class Application {
  }"
 but was: 
  "import org.springframework.boot.autoconfigure.SpringBootApplication;
  
  
  @SpringBootApplication
  public class Application {
  }"
```

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

I’m not entirely sure what the underlying issue is, but I would be happy to contribute a fix if you can provide some guidance on how to resolve it.
