### ISSUE TITLE
Flyway 10 migration for PostgreSQL

### ISSUE THREAD

**Issue by ghusta** [openrewrite/rewrite-spring#731]
In order to fix https://github.com/openrewrite/rewrite-spring/issues/532 (at least partially), I suggest to do it step by step, as Flyway 10 contains multiple modules, one per database.
So #532 could be a kind of umbrella issue, or this one a sub-issue.

My idea is to include a parent recipe which could be named `org.openrewrite.java.spring.boot3.MigrateToFlyway10` into [org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_3](https://github.com/openrewrite/rewrite-spring/blob/main/src/main/resources/META-INF/rewrite/spring-boot-33.yml). Indeed [Flyway 10 was introduced in Spring Boot 3.3](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes#flyway-10).

Then, `org.openrewrite.java.spring.boot3.MigrateToFlyway10` could contain another declarative recipe named `org.openrewrite.java.spring.boot3.MaybeAddFlywayModules`.

Finally, `org.openrewrite.java.spring.boot3.MaybeAddFlywayModules` would contain multiple declarative recipes, one for each database.
For example, let's begin with `org.openrewrite.java.spring.boot3.MaybeAddFlywayModulePostgresql`.

Here is my first proposal for these first 3 recipes :

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot3.MigrateToFlyway10
displayName: Migrate to Flyway 10
description: >-
  Migrate to Flyway 10. 
  See details at [Flyway V10 has landed](https://documentation.red-gate.com/fd/flyway-v10-has-landed-222627771.html).
tags:
  - flyway
recipeList:
  - org.openrewrite.java.spring.boot3.MaybeAddFlywayModules
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot3.MaybeAddFlywayModules
displayName: Add missing Flyway modules (from Flyway 10)
description: >-
  Multiple db modules formerly part of flyway core have been separated out in to their own modules for increased flexibility. 
  Full details can be found at https://github.com/flyway/flyway/issues/3780.
tags:
  - flyway
recipeList:
  - org.openrewrite.java.spring.boot3.MaybeAddFlywayModulePostgresql
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.spring.boot3.MaybeAddFlywayModulePostgresql
displayName: Add missing Flyway module for PostgreSQL `flyway-database-postgresql` (from Flyway 10)
tags:
  - flyway
preconditions:
  - org.openrewrite.java.dependencies.DependencyInsight:
      groupIdPattern: org.flywaydb
      artifactIdPattern: flyway-core
      version: "[10,)"
  - org.openrewrite.java.dependencies.DependencyInsight:
      groupIdPattern: org.postgresql
      artifactIdPattern: postgresql
recipeList:
  - org.openrewrite.maven.AddDependency:
      groupId: org.flywaydb
      artifactId: flyway-database-postgresql
      version: LATEST
  - org.openrewrite.gradle.AddDependency:
      groupId: org.flywaydb
      artifactId: flyway-database-postgresql
      version: LATEST
```

It seems to be working after my first tests.
If it's OK, I could add another recipes for MySQL, Oracle, etc.

Any suggestion appreciated.

---

- Parent issue : #532
