### ISSUE TITLE
Flyway 10 migration for Oracle

### ISSUE THREAD

**Issue by ghusta** [openrewrite/rewrite-spring#733]
Similar to #731, but for Oracle databases.

It aims to be a sub-issue of #532.

The recipe to include in `flyway-10.yml` should be something like:

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.flyway.MaybeAddFlywayModuleOracle
displayName: Add missing Flyway module for Oracle DB
description: >-
  Database modules for Flyway 10 have been split out in to separate modules for maintainability.
  Add the `flyway-database-oracle` dependency if you are using Oracle DB with Flyway 10,
  as detailed on https://github.com/flyway/flyway/issues/3780.
tags:
  - flyway
  - oracle
preconditions:
  - org.openrewrite.java.dependencies.DependencyInsight:
      groupIdPattern: org.flywaydb
      artifactIdPattern: flyway-core
      version: "[10,)"
  - org.openrewrite.java.dependencies.DependencyInsight:
      groupIdPattern: com.oracle.database.jdbc
      artifactIdPattern: ojdbc*
recipeList:
  - org.openrewrite.java.dependencies.AddDependency:
      groupId: org.flywaydb
      artifactId: flyway-database-oracle
      acceptTransitive: true
```
