### ISSUE TITLE
Flyway 10 migration for MySQL

### ISSUE THREAD

**Issue by ghusta** [openrewrite/rewrite-spring#734]
Similar to #731, but for MySQL databases.

It aims to be a sub-issue of #532.

The recipe to include in `flyway-10.yml` should be something like:

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.flyway.MaybeAddFlywayModuleMysql
displayName: Add missing Flyway module for MySQL `flyway-mysql` (from Flyway 10)
description: >-
  Multiple db modules formerly part of flyway core have been separated out in to their own modules for increased flexibility. 
  Full details can be found at https://github.com/flyway/flyway/issues/3780.
tags:
  - flyway
preconditions:
  - org.openrewrite.java.dependencies.DependencyInsight:
      groupIdPattern: org.flywaydb
      artifactIdPattern: flyway-core
      version: "[10,)"
  - org.openrewrite.java.dependencies.DependencyInsight:
      groupIdPattern: com.mysql
      artifactIdPattern: mysql-connector-j
recipeList:
  - org.openrewrite.java.dependencies.AddDependency:
      groupId: org.flywaydb
      artifactId: flyway-mysql
```
