### ISSUE TITLE
Flyway 10 migration for SQL Server

### ISSUE THREAD

**Issue by ghusta** [openrewrite/rewrite-spring#738]
Similar to #731, but for MS SQL Server databases.

- It aims to be a sub-issue of #532.

The recipe to include in `flyway-10.yml` should be something like:

```yaml
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.flyway.MaybeAddFlywayModuleSqlserver
displayName: Add missing Flyway module for SQL Server
description: >-
  Database modules for Flyway 10 have been split out into separate modules for maintainability.
  Add the `flyway-sqlserver` dependency if you are using SQL Server with Flyway 10,
  as detailed on https://github.com/flyway/flyway/issues/3780.
tags:
  - flyway
  - sqlserver
preconditions:
  - org.openrewrite.java.dependencies.DependencyInsight:
      groupIdPattern: org.flywaydb
      artifactIdPattern: flyway-core
      version: "[10,)"
  - org.openrewrite.java.dependencies.DependencyInsight:
      groupIdPattern: com.microsoft.sqlserver
      artifactIdPattern: mssql-jdbc
recipeList:
  - org.openrewrite.java.dependencies.AddDependency:
      groupId: org.flywaydb
      artifactId: flyway-sqlserver
      acceptTransitive: true
```
